version: '3.8'

services:
  api:
    container_name: ojb.bank_api
    build: .
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    ports:
      - 5000:5000
    volumes:
      - .:/app
    networks:
      - objbank-network
  db:
    container_name: obj.bank_db
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=obj_bank_db
    networks:
      - objbank-network

volumes:
  postgres_data:

networks: 
  objbank-network:
    driver: bridge

# docker-compose up -d
